### Why Sample Variance is dividen by n-1


As we takethe sample randomly so sometime we take sample only from one area then it will become bias then in order to make it unbiased we divide it by n-1



In [ ]:
### Chi Square Test

It's non-parametric test, that is perform on Categorical Data

Step1 : H0, Accept the null hypothesis

Step2 : H1, Reject the null hypothesis    
    
Step3 : α=.05 then CI 95%
    
Step4 : Degree of freedom => n-1
    
Step5 : CHI-Square= Σ(f0 - fe)**2/  fe
    

In [15]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np


In [16]:
dataset= sns.load_dataset('tips')


In [17]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Chi Square Test

The test is applied when you have two categorical variable from a single population.

It's used to determine whether there is a significant association b/w two variables or not.


In [18]:
dataset_table= pd.crosstab(dataset['sex'], dataset['smoker'])
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [20]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [21]:
#Now Observed vale

observed_value= dataset_table.values
observed_value

array([[60, 97],
       [33, 54]], dtype=int64)

In [24]:
# Then come to expected values

val= stats.chi2_contingency(dataset_table)
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [26]:
# Take the 3rd as it's our expected values

expected_values=val[3]
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [31]:
# For calculationg degree of freedom

no_of_rows= len(dataset_table.iloc[0:2,0])
#print(no_of_rows)

no_of_columns = len(dataset_table.iloc[0,0:2])
#print(no_of_columns)


ddof= (no_of_columns-1)*(no_of_rows-1)

print("Degree of freedom: ",ddof)

alpha=0.05




Degree of freedom:  1


In [ ]:
# Let's apply Chi Sqaure Formula



## Anova Test-----(F-Test)

The t-test work well if you are dealing with 2 groups. But what if you have more than 2 groups?

Then F-test(Anova test) come into the picture



Exp:-  There are 3 diff category of iris flower & their petal length, we need to check whether all 3 groups are similar or not?
    
    
    



In [33]:
df1= sns.load_dataset('iris')
df1.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
df_anova= df1[['petal_width','species']]



In [37]:
grps = pd.unique(df_anova.species.values)
grps


array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [39]:
d_data = { grp: df_anova['petal_width'][df_anova.species==grp]  for grp in grps}

In [40]:
d_data

{'setosa': 0     0.2
 1     0.2
 2     0.2
 3     0.2
 4     0.2
 5     0.4
 6     0.3
 7     0.2
 8     0.2
 9     0.1
 10    0.2
 11    0.2
 12    0.1
 13    0.1
 14    0.2
 15    0.4
 16    0.4
 17    0.3
 18    0.3
 19    0.3
 20    0.2
 21    0.4
 22    0.2
 23    0.5
 24    0.2
 25    0.2
 26    0.4
 27    0.2
 28    0.2
 29    0.2
 30    0.2
 31    0.4
 32    0.1
 33    0.2
 34    0.2
 35    0.2
 36    0.2
 37    0.1
 38    0.2
 39    0.2
 40    0.3
 41    0.3
 42    0.2
 43    0.6
 44    0.4
 45    0.3
 46    0.2
 47    0.2
 48    0.2
 49    0.2
 Name: petal_width, dtype: float64,
 'versicolor': 50    1.4
 51    1.5
 52    1.5
 53    1.3
 54    1.5
 55    1.3
 56    1.6
 57    1.0
 58    1.3
 59    1.4
 60    1.0
 61    1.5
 62    1.0
 63    1.4
 64    1.3
 65    1.4
 66    1.5
 67    1.0
 68    1.5
 69    1.1
 70    1.8
 71    1.3
 72    1.5
 73    1.2
 74    1.3
 75    1.4
 76    1.4
 77    1.7
 78    1.5
 79    1.0
 80    1.1
 81    1.0
 82    1.2
 83    1.6
 84    1.5
 85  

In [41]:
f,p = stats.f_oneway(d_data['setosa'], d_data['versicolor'],d_data['virginica'])

In [44]:
#f
p

4.169445839443116e-85

In [45]:
if p<0.05:
    print("Accept Null Hypothesis")
else:
    print("Reject Null Hypothesis")

Accept Null Hypothesis
